service: default
runtime: custom
env: flex

resources:
    cpu: 4
    memory_gb: 4
    disk_size_gb: 0

liveness_check:
    path: /health

readiness_check:
    path: /health

network:
    # session_affinity: true
    forwarded_ports:
        - 17486/tcp
