version: "3.6"
services:
    db:
        image: mongo:latest
        restart: always
        #volumes:
        #    - ./db:/data/db
    web:
        image: tivolicloud/metaverse:latest
        restart: always
        ports:
            - 3000:3000/tcp
        environment:
            DB_HOST: db
