version: "3.6"
services:
    db:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db
            - ./mongodump:/mongodump
    # web:
    #     image: tivolicloud/metaverse:latest
    #     restart: always
    #     ports:
    #         - 3000:3000/tcp
    #     environment:
    #         DB_HOST: db
